version: "3.9"

name: kaliboxnetwork

services:

  kalibox:
    container_name: KaliBox
    build: ./kalibox
    ports:
     - "4000:22"
    entrypoint: "/box/init.sh toor kali"

  nodeproxy:
    container_name: WSSProxy
    build: .
    links:
      - "kalibox:kali"
    ports:
      - "3000:3000"
    environment:
      - PORT=3000